"use client";
import { useMemo, useState } from "react";

type Entry={year:string;title:string;category:string;era:string;summary:string;accent:string;slug?:string};
const entries:Entry[]=[
{year:"c. 300",title:"The Kingdom of Aksum",category:"Civilizations",era:"Ancient Africa",summary:"A major trading power connected Africa, Arabia, and the Mediterranean—and minted its own remarkable currency.",accent:"gold",slug:"/stories/kingdom-of-aksum"},
{year:"1324",title:"Mansa Musa’s Pilgrimage",category:"Leaders",era:"Medieval Africa",summary:"The ruler of Mali crossed North Africa on a journey that revealed the scale, learning, and wealth of his empire.",accent:"copper",slug:"/stories/mansa-musa-pilgrimage"},
{year:"1804",title:"Haiti Declares Independence",category:"Revolutions",era:"Resistance & Freedom",summary:"The Haitian Revolution created the world’s first independent Black republic and shattered the logic of colonial slavery.",accent:"red"},
{year:"1849",title:"Harriet Tubman Escapes",category:"People",era:"Resistance & Freedom",summary:"After reaching freedom, Tubman repeatedly returned south, guiding others along the Underground Railroad.",accent:"green"},
{year:"1921",title:"The Greenwood District",category:"Communities",era:"Reconstruction & Renaissance",summary:"Tulsa’s prosperous Black community built a powerful local economy before racial terror devastated the district.",accent:"blue"},
{year:"1955",title:"The Montgomery Bus Boycott",category:"Movements",era:"Civil Rights Era",summary:"A 381-day mass protest challenged segregated transit and demonstrated the power of sustained community organizing.",accent:"violet"},
{year:"1966",title:"The Black Panther Party",category:"Movements",era:"Black Power Era",summary:"Founded in Oakland, the organization paired political self-determination with community survival programs.",accent:"charcoal"},
{year:"2008",title:"A Historic Presidential Election",category:"Politics",era:"Contemporary",summary:"Barack Obama’s election as the 44th U.S. president marked an unprecedented milestone in American political history.",accent:"indigo"}];
const eras=["All eras","Ancient Africa","Medieval Africa","Resistance & Freedom","Reconstruction & Renaissance","Civil Rights Era","Black Power Era","Contemporary"];

export default function Home(){
 const [query,setQuery]=useState(""); const [era,setEra]=useState("All eras");
 const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return entries.filter(e=>(era==="All eras"||e.era===era)&&(!n||`${e.title} ${e.summary} ${e.category} ${e.year}`.toLowerCase().includes(n)))},[query,era]);
 return <main>
  <header className="site-header"><a className="brand" href="#top" aria-label="The Black History Codex home"><span className="brand-mark">BHC</span><span><strong>The Black History</strong><em>Codex</em></span></a><nav aria-label="Main navigation"><a href="#explore">Explore</a><a href="#timeline">Timeline</a><a href="#mission">About</a></nav><a className="nav-cta" href="#explore">Open the Codex ↗</a></header>
  <section className="hero" id="top"><div className="hero-lines"/><div className="eyebrow">✦ Knowledge preserved. Stories reclaimed.</div><h1>History didn’t<br/>begin with <em>bondage.</em></h1><p className="hero-copy">Explore the people, civilizations, movements, and ideas that shaped the Black experience—across centuries and continents.</p><div className="hero-actions"><a className="button primary" href="#explore">Explore the collection →</a><a className="button ghost" href="#timeline">Browse the timeline</a></div><div className="hero-stats"><div><strong>3,000+</strong><span>Years of history</span></div><div><strong>6</strong><span>Continents connected</span></div><div><strong>∞</strong><span>Stories to preserve</span></div></div></section>
  <section className="manifesto" id="mission"><p className="section-number">01 / THE MISSION</p><blockquote>“A people without the knowledge of their past history, origin and culture is like a tree without roots.”</blockquote><p className="attribution">— Marcus Garvey</p><div className="mission-copy"><h2>More than a month.<br/><em>A living archive.</em></h2><p>The Black History Codex is being built as a welcoming, source-conscious place to learn beyond the familiar headlines. It connects African antiquity, the diaspora, resistance, achievement, culture, and the unfinished work of freedom.</p></div></section>
  <section className="explore" id="explore"><div className="section-heading"><div><p className="section-number">02 / EXPLORE THE CODEX</p><h2>Find a story that<br/>changes your <em>perspective.</em></h2></div><p>Start with a name, a movement, a place, or an idea. This first collection establishes the structure for a much larger historical library.</p></div>
   <div className="search-panel"><label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people, events, movements…" aria-label="Search the Codex"/></label><select value={era} onChange={e=>setEra(e.target.value)} aria-label="Filter by historical era">{eras.map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="result-meta"><span>{filtered.length} {filtered.length===1?"entry":"entries"}</span><span>{era}</span></div><div className="card-grid">{filtered.map(e=><article className={`story-card ${e.accent}`} key={e.title}><div className="card-top"><span className="year">{e.year}</span><span className="category">{e.category}</span></div><div className="card-symbol"><span>{e.title.charAt(0)}</span></div><p className="era">{e.era}</p><h3>{e.title}</h3><p>{e.summary}</p>{e.slug?<a className="story-link" href={e.slug} aria-label={`Read about ${e.title}`}>Read the story <span>→</span></a>:<span className="story-link coming">Article coming soon <span>○</span></span>}</article>)}</div>{filtered.length===0&&<div className="empty"><strong>No entries found—yet.</strong><p>Try a broader search or choose another era.</p></div>}</section>
  <section className="timeline" id="timeline"><div className="timeline-intro"><p className="section-number">03 / THROUGH TIME</p><h2>One history.<br/><em>Countless chapters.</em></h2><p>Move across a connected story—from kingdoms and trade routes to liberation movements and cultural revolutions.</p></div><div className="timeline-track">{entries.slice(0,6).map((e,i)=><div className="timeline-item" key={e.year}><span>{String(i+1).padStart(2,"0")}</span><strong>{e.year}</strong><p>{e.title}</p></div>)}</div></section>
  <section className="newsletter"><span className="seal">✦</span><p className="section-number">KEEP LEARNING</p><h2>History belongs<br/>to those who <em>remember.</em></h2><p>New stories, timelines, and learning resources are coming as the Codex grows.</p><form onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Enter your email address"/><button type="submit">Join the archive →</button></form></section>
  <footer><a className="brand" href="#top"><span className="brand-mark">BHC</span><span><strong>The Black History</strong><em>Codex</em></span></a><p>Preserving the past. Informing the present. Inspiring the future.</p><p>© 2026 The Black History Codex</p></footer>
 </main>
}
