import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Black Panther Party | The Black History Codex",
  description: "How the Black Panther Party joined self-defense and political education to food, health, schooling, and coalition building.",
  openGraph: { title: "The Black Panther Party", description: "Beyond the berets: self-determination, survival programs, women’s leadership, coalition, repression, and legacy.", images: [{ url: "https://black-history-codex.kenshinsega.chatgpt.site/black-panther-hero.png", width: 1536, height: 1024, alt: "Editorial illustration of a Black Panther community breakfast program" }] },
  twitter: { card: "summary_large_image", title: "The Black Panther Party", description: "Beyond the berets: community programs, political struggle, and a contested legacy.", images: ["https://black-history-codex.kenshinsega.chatgpt.site/black-panther-hero.png"] },
};

const facts = [["Founded","October 1966"],["Place","Oakland, California"],["Founders","Huey P. Newton and Bobby Seale"],["Active","1966–1982"]];
const milestones = [
  ["October 1966","Newton and Seale found the party in Oakland and develop its Ten-Point Program."],
  ["May 1967","Armed Panthers protest at the California State Capitol as legislators debate limits on openly carrying firearms."],
  ["1968","The party expands beyond Oakland as chapters and its newspaper reach a national audience."],
  ["January 1969","The first Free Breakfast for Children program opens at an Oakland church."],
  ["December 4, 1969","Chicago police kill Fred Hampton and Mark Clark in a predawn raid shaped by FBI intelligence."],
  ["1971","A major split between Newton and Eldridge Cleaver deepens amid repression, exile, and strategic conflict."],
  ["1974","Elaine Brown becomes party chair and leads an organization increasingly focused on Oakland politics and institutions."],
  ["1982","The Oakland Community School closes; the party’s formal history comes to an end."],
];

export default function BlackPantherStory(){return <main className="article-page panther-page">
  <header className="article-header"><a className="brand" href="/" aria-label="The Black History Codex home"><span className="brand-mark">BHC</span><span><strong>The Black History</strong><em>Codex</em></span></a><a className="back-link" href="/#explore">← Back to the collection</a></header>
  <article>
    <section className="article-hero"><div className="article-kicker">Movements <span>•</span> Black Power Era <span>•</span> 1966–1982</div><h1>The Black Panther<br/><em>Party</em></h1><p>It watched the police, fed children, opened clinics, built coalitions, and forced the country to confront what community power could mean.</p><div className="article-hero-art panther-art" role="img" aria-label="Editorial illustration of Black Panther Party members serving children and families at a community breakfast program"><span>Original editorial illustration</span></div></section>
    <section className="article-facts" aria-label="Key facts">{facts.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <div className="article-layout"><aside className="article-nav"><p>In this entry</p><a href="#overview">01 — Overview</a><a href="#oakland">02 — Oakland origins</a><a href="#program">03 — Ten points</a><a href="#patrols">04 — Armed patrols</a><a href="#survival">05 — Survival programs</a><a href="#women">06 — Women and gender</a><a href="#coalitions">07 — Coalitions</a><a href="#repression">08 — Repression and conflict</a><a href="#legacy">09 — Legacy</a><a href="#sources">Sources</a></aside>
      <div className="article-body">
        <section id="overview"><p className="chapter-label">01 / OVERVIEW</p><h2>Beyond the berets</h2><p className="lead">The Black Panther Party became one of the most recognizable—and most contested—organizations of the Black Power era. Its public image of armed self-defense was real, but incomplete.</p><p>The Panthers connected police accountability to housing, food, education, health, employment, and political power. Their chapters built practical institutions while arguing that poverty and police violence were not isolated failures: they were produced by systems that communities could organize to change.</p></section>
        <section id="oakland"><p className="chapter-label">02 / OAKLAND ORIGINS</p><h2>A local answer to structural violence</h2><p>Huey P. Newton and Bobby Seale founded the Black Panther Party for Self-Defense in Oakland in October 1966. The city’s growing Black population faced job discrimination, inadequate housing, urban displacement, and repeated conflict with police.</p><p>The founders studied anticolonial movements, Black nationalism, socialism, and community organizing. They sought a disciplined organization that could document police conduct, teach political history, and build independent power rather than wait for institutions to reform themselves.</p></section>
        <section id="program"><p className="chapter-label">03 / THE TEN-POINT PROGRAM</p><h2>Demands and a political map</h2><p>The party’s Ten-Point Program called for self-determination, full employment, decent housing, meaningful education, an end to police brutality, and justice in courts and prisons. It linked immediate needs to a wider analysis of capitalism, racism, and imperial power.</p><p>The platform was both a list of demands and an organizing tool. Members sold newspapers, held political education classes, recruited neighbors, and used the program to frame everyday hardship as a public question of power.</p></section>
        <section id="patrols"><p className="chapter-label">04 / ARMED PATROLS</p><h2>Watching those who watched the neighborhood</h2><p>Early Panthers followed police activity in Oakland, observed arrests, informed residents of legal rights, and—under California law at the time—openly carried firearms. The patrols asserted that police power could be monitored and challenged, while their visibility also created danger and intense controversy.</p><p>In May 1967, armed members entered the California State Capitol to oppose a bill restricting open carry. The event brought national attention; the Mulford Act soon became law. Images of weapons often eclipsed the party’s larger program and made it easier for officials and media to define the organization only through confrontation.</p></section>
        <blockquote className="article-quote">The Panthers understood that power meant watching the police—and feeding a child before school.</blockquote>
        <section id="survival"><p className="chapter-label">05 / SURVIVAL PROGRAMS</p><h2>Meeting needs while building power</h2><p>Beginning with an Oakland church breakfast in January 1969, the Free Breakfast for Children program spread through Panther chapters. Volunteers gathered food, prepared meals, taught political lessons, and sent children to school fed.</p><p>The party created many other “survival pending revolution” programs: groceries for families and elders, clothing, transportation, legal aid, liberation schools, health clinics, and sickle-cell anemia testing. The Smithsonian records that Panther breakfast programs at their height fed thousands of children each day.</p><div className="insight-card"><span>Why “survival” mattered</span><p>These programs offered immediate care, but they were not conceived as charity alone. They exposed unmet public obligations, demonstrated collective capacity, and gave neighbors a place to organize.</p></div></section>
        <section id="women"><p className="chapter-label">06 / WOMEN & GENDER</p><h2>Essential leaders in an unequal organization</h2><p>Women became a majority of the party’s membership and ran chapters, newspapers, schools, clinics, food programs, and political education. Elaine Brown later chaired the national organization; Ericka Huggins, Kathleen Cleaver, and many less-famous members shaped its strategy and public life.</p><p>Their leadership existed alongside sexism. Women confronted unequal authority, gendered labor, harassment, and rhetoric that sometimes reproduced the domination the party opposed. They challenged those contradictions from within, redefining revolutionary leadership through caregiving, administration, education, and armed political work.</p></section>
        <section id="coalitions"><p className="chapter-label">07 / COALITIONS & INTERNATIONALISM</p><h2>Solidarity across boundaries</h2><p>Panthers connected Black liberation in the United States to anticolonial struggles abroad. In Chicago, Fred Hampton helped build the original Rainbow Coalition with the Puerto Rican Young Lords and the poor white Young Patriots, while negotiating a truce among neighborhood groups.</p><p>These alliances did not erase profound differences. They argued that communities could organize across race around police violence, poverty, housing, and political control without abandoning their distinct identities.</p></section>
        <section id="repression"><p className="chapter-label">08 / REPRESSION & INTERNAL CONFLICT</p><h2>A movement under assault—and strain</h2><p>Police departments and the FBI targeted the party with surveillance, raids, prosecutions, informants, and covert disruption. Under COINTELPRO, agents exploited rivalries and sent forged communications. On December 4, 1969, Chicago police killed Fred Hampton and Mark Clark during a predawn raid after an FBI informant supplied details of Hampton’s apartment.</p><p>State repression was devastating, but it was not the only source of decline. Deaths, imprisonment, exile, ideological disagreements, centralized authority, strategic disputes, violence, sexism, exhaustion, and the 1971 Newton–Cleaver split fractured the organization. Any honest account must hold external attack and internal contradiction together.</p></section>
        <section id="legacy"><p className="chapter-label">09 / MEANING & LEGACY</p><h2>What the Panthers changed</h2><ul className="significance-list"><li><strong>They broadened public safety.</strong><span>Police accountability was tied to food, health, housing, education, and community control.</span></li><li><strong>They made care political.</strong><span>Breakfasts and clinics met urgent needs while showing what organized communities could build.</span></li><li><strong>Women remade the organization.</strong><span>The party’s history cannot be understood through male leaders or armed imagery alone.</span></li><li><strong>Coalition became strategy.</strong><span>Panthers built alliances across racial and national lines around shared material struggles.</span></li><li><strong>Repression left a warning.</strong><span>The documented campaign against the party shows how state power can undermine lawful dissent and organizing.</span></li></ul></section>
        <section className="mini-timeline"><p className="chapter-label">A BRIEF TIMELINE</p>{milestones.map(([year,event])=><div key={year}><strong>{year}</strong><p>{event}</p></div>)}</section>
        <section className="sources" id="sources"><p className="chapter-label">SOURCES & FURTHER READING</p><h2>Continue exploring</h2><p>This entry treats the party as both a political organization and a network of community institutions. FBI files are included as records of state surveillance, not as neutral descriptions of the Panthers.</p><ol>
          <li><a href="https://nmaahc.si.edu/explore/stories/black-panther-party-challenging-police-and-promoting-social-change" target="_blank" rel="noreferrer"><strong>Smithsonian NMAAHC</strong><span>The party, police accountability, and survival programs ↗</span></a></li>
          <li><a href="https://nmaahc.si.edu/explore/stories/black-panther-party-uniform" target="_blank" rel="noreferrer"><strong>Smithsonian NMAAHC</strong><span>Women, gender, style, and self-determination ↗</span></a></li>
          <li><a href="https://www.archives.gov/research/african-americans/black-power/black-panthers" target="_blank" rel="noreferrer"><strong>National Archives</strong><span>Black Panther Party records and leaders ↗</span></a></li>
          <li><a href="https://www.archives.gov/research/african-americans/individuals/fred-hampton" target="_blank" rel="noreferrer"><strong>National Archives</strong><span>Fred Hampton, community programs, and coalition ↗</span></a></li>
          <li><a href="https://www.loc.gov/item/2016655436/" target="_blank" rel="noreferrer"><strong>Library of Congress</strong><span>Elbert Howard oral history ↗</span></a></li>
          <li><a href="https://vault.fbi.gov/cointel-pro" target="_blank" rel="noreferrer"><strong>FBI Vault</strong><span>Primary records from the COINTELPRO surveillance program ↗</span></a></li>
        </ol></section>
        <nav className="story-pagination" aria-label="Story navigation"><a href="/stories/montgomery-bus-boycott">← The Montgomery Bus Boycott</a><span>Next story<br/><strong>A Historic Presidential Election →</strong></span></nav>
      </div>
    </div>
  </article>
</main>}
